# 允许空白 Issue（如果需要）
blank_issues_enabled: true

# Issues 页面顶部的介绍文字
contact_links:
  - name: 资源贡献指南
    url: https://github.com/guomengtao/rinuo.com/blob/main/CONTRIBUTING.md  # 可选：链接到详细指南
    about: 请先阅读资源贡献的规范和流程，再提交新内容哦！

  - name: 常见问题
    url: https://github.com/guomengtao/rinuo.com/issues?q=is%3Aissue+is%3Aclosed+label%3A%22FAQ%22
    about: 查看已解决的常见问题，避免重复提问~
