name: Auto Movie HTML Generator

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour, on the hour UTC
  workflow_dispatch:

jobs:
  generate_html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set date and hour variables
        id: vars
        run: |
          export DATE=$(date -u +"%Y%m%d")
          export HOUR=$(date -u +"%H")
          echo "date=${DATE}" >> $GITHUB_OUTPUT
          echo "hour=${HOUR}" >> $GITHUB_OUTPUT

      - name: Pick a YouTube movie
        id: movie
        run: |
          MOVIES=(
            "https://www.youtube.com/embed/dQw4w9WgXcQ"
            "https://www.youtube.com/embed/2Vv-BfVoq4g"
          )
          RANDOM_INDEX=$((RANDOM % ${#MOVIES[@]}))
          MOVIE_URL="${MOVIES[$RANDOM_INDEX]}"
          echo "movie_url=$MOVIE_URL" >> $GITHUB_OUTPUT

      - name: Generate HTML file
        run: |
          mkdir -p auto-job
          FILENAME="auto-job/${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.hour }}.html"
          cat > $FILENAME <<EOF
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Free Movie Hour</title>
          </head>
          <body>
            <h1>Enjoy a Free Movie!</h1>
            <iframe width="560" height="315" src="${{ steps.movie.outputs.movie_url }}" title="YouTube video player" frameborder="0" allowfullscreen></iframe>
            <p>Generated at UTC hour: ${{ steps.vars.outputs.hour }} on ${{ steps.vars.outputs.date }}</p>
          </body>
          </html>
          EOF

      - name: Commit and push new HTML file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add auto-job/
          git commit -m "Auto-create movie HTML for ${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.hour }}"
          git push
